import "./components/slideProduct.js";
import "./components/stepper.js";
import "./components/swiper.js";
import "./components/dropdown.js";
import "./components/catalog.js";
import "./components/cart.js";
import "./components/maps.js";
import "./components/order.js";
import "./components/block-row.js";
